<a href="https://colab.research.google.com/github/shatakshii25/Python-and-ML-Practice-Notebooks/blob/main/class7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# File handling, Numpy and Matplotlib

In [ ]:
# writefile is a magic command for easier file creation using python
%%writefile abc.txt 
qwert1324
12345656592
62566+5
35598566

Overwriting abc.txt


In [ ]:
%%writefile abc.py 
def calc(n1,n2):
  print("sum = ", n1+n2)
  print("difference = ", n1-n2)
  print("product = ", n1*n2)
  print("quotient = ", n1/n2)

calc(7,5)

Writing abc.py


In [ ]:
# create a file
f1 = open("demo.txt","w") #write mode (to create a file)
print(f1)
# UTF-8 is a variable-width character encoding used for electronic communication

<_io.TextIOWrapper name='demo.txt' mode='w' encoding='UTF-8'>


In [ ]:
f1 = open("demo.txt","a") #append or add data to the file
f1.write("welcome to google colaboratory!\n")
f1.write("Have fun learning python!")

25

In [ ]:
f1 = open("demo.txt", "r")
print(f1.read())

welcome to google colaboratory!Have fun learning python!


In [ ]:
# NUMPY - NUMERICAL PYTHON (library in python)

In [ ]:
# arrays 
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np #importing the library to use it

In [ ]:
# 0 dimensions
a0 = np.array(45)
type(a0)
a0.ndim #number of dimensions

# 1 dimensions
a1 = np.array([1,2,3,4,5])
a1.ndim 

# 2 dimensions
a2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
a2
a2.ndim

# 3 dimensions
a3 = np.array([[[1,2,3,4,5],[6,7,8,9,10]]])
a3.ndim
a3

# 4 dimensions
a4 = np.array([[[[1,2,3,4,5],[6,7,8,9,10]]]])
a4.ndim
a4

# # Higher dimensions
# arr_high = np.array([4,5,3,2,6],ndim=10)
# arr_high.ndim

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]]])

In [ ]:
a = np.array([7,5,6,2,4,3,1])
a

array([7, 5, 6, 2, 4, 3, 1])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.ndim #1 dimension

1

In [ ]:
a.size #count of all the elements in the numpy array

7

In [ ]:
a.dtype #integer 64-bits (by default 64 bits)

dtype('int64')

In [ ]:
a.shape

(7,)

In [ ]:
a

array([7, 5, 6, 2, 4, 3, 1])

In [ ]:
a[2:6]

array([6, 2, 4, 3])

In [ ]:
b = np.array([2,5,6,8,9,2,1])
b

array([2, 5, 6, 8, 9, 2, 1])

In [ ]:
a

array([7, 5, 6, 2, 4, 3, 1])

In [ ]:
b

array([2, 5, 6, 8, 9, 2, 1])

In [ ]:
a+b

array([ 9, 10, 12, 10, 13,  5,  2])

In [ ]:
a-b

array([ 5,  0,  0, -6, -5,  1,  0])

In [ ]:
a*b

array([14, 25, 36, 16, 36,  6,  1])

In [ ]:
a%b

array([1, 0, 0, 2, 4, 1, 0])

In [ ]:
a//b

array([3, 1, 1, 0, 0, 1, 1])

In [ ]:
a[6]+b[-3]

10

In [ ]:
# broadcasting an array
a*5

array([35, 25, 30, 10, 20, 15,  5])

In [ ]:
a/3

array([2.33333333, 1.66666667, 2.        , 0.66666667, 1.33333333,
       1.        , 0.33333333])

In [ ]:
a = np.array([7.0,5.0,6.0,2.0,4.0,3.0,1.0])
a.dtype

dtype('float64')

In [ ]:
a = np.array([7.0,5.0,6.0,2.0,4.0,3.0,1.0], dtype ='int')
a.dtype

dtype('int64')

In [ ]:
a

array([7, 5, 6, 2, 4, 3, 1])

In [ ]:
b

array([2, 5, 6, 8, 9, 2, 1])

In [ ]:
max(a)

7.0

In [ ]:
np.max(a)

7.0

In [ ]:
np.min(a)

1.0

In [ ]:
np.sum(a)

28.0

In [ ]:
np.mean(a) #average is returned

4.0

In [ ]:
np.zeros(10) #10 zeros to be created

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros([10,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros([10,10], dtype = 'int') #by default datatype is float64, if we want, we can change

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones([10,10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.ones([10,10], dtype='int64')

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])